disabled_rules: # rule identifiers to exclude from running
 - trailing_whitespace
 - multiple_closures_with_trailing_closure
excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods
 
line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

identifier_name:
    min_length: 2

